
- name: Download Lua
  get_url:
    url: "https://www.lua.org/ftp/lua-5.4.7.tar.gz"
    dest: /tmp/discord.deb
  tags:
    - minimal-install
    - install
    - discord

- name: Install Discord
  become: true
  apt:
    deb: /tmp/discord.deb
    state: present
  tags:
    - minimal-install
    - install
    - discord

- name: Remove Discord .deb package
  file:
    path: /tmp/discord.deb
    state: absent
  tags:
    - minimal-install
    - install
    - discord
