- name: Creates a directory for Neovim
  file:
    path: /opt
    state: directory

- name: Download and extract Neovim
  unarchive: 
    src: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
    dest: /opt
    remote_src: yes

- name: Add Neovim to path 
  become_user: root
  replace:
    path: /etc/environment
    regexp: 'PATH="(?!\/opt\/nvim-linux64/bin:)'
    replace: 'PATH="/opt/nvim-linux64/bin:'
  when: 
