- name: ensure that Ubuntu Universe repository is enabled
  become: true
  apt:
    name: software-properties-common

- name: add the Ubuntu Universe Repository
  shell:
    cmd: add-apt-repository universe -y

- name: make sure curl is installed
  apt: 
    name: curl
    update_cache: yes

- name: add the ROS2 GPG key with apt, and add the repository to sources list
  shell:
    cmd: |
      curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

- name: Update and upgrade apt packages
  become: true
  apt: 
    upgrade: yes
    update_cache: yes

- name: Install ROS2 packages and developer tools
  apt:
    name: 
      - ros-humble-desktop
      - python3-colcon-common-extensions
      - python3-rosdep2


- name: Enable ros2 in bashrc
  blockinfile:
    path: "/home/{{ user }}/.bashrc"
    block: |
      echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc


